# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ios-test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-test
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireObjectMapper', '~> 5.0'

  target 'ios-testTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
