platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

def shared_pods
end

target 'CatchTestSam' do
	use_frameworks!
	pod 'SwiftyJSON'
	pod 'Refreshable'
	target :CatchTestSamTests
end
