# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!


def common_pods
	pod 'NVActivityIndicatorView', '3.6.1'
end

target 'CatchTest' do

	common_pods

end

target 'CatchTestTests' do 

	common_pods

end