# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'CatchDesignTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CatchDesignTest
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
	
end
